### ISSUE TITLE
Does it support splits and spin-offs?

### ISSUE THREAD

**Issue by piotrfonte** [dpuljic01/revolut-statements#1]
Hi,

I wonder if the app caters for split stock shares (like Tesla, Apple) and spin-offs (like Pfizer’s VTRS). Asking because I keep on getting `Internal Server Error` and not sure why.

Thanks!

**Comment by dpuljic01** [comment]
@piotrf  For now, I just export what's inside of the pdfs, it's up to the user to play  with that excel file and adjust their formulas for anything extra. However, I do plan to extend this and also have an UI. Once when I have that ready I'll implement additional calculations :)
PS: If you still got that error message, is it possible to post the output from terminal here?
